### ISSUE TITLE
[Request] Update to latest OSSC Pro changes

### ISSUE THREAD

**Issue by MP2E** [marqs85/DExx-vd_isl#4]
Hi there, thank you for your work on the OSSC standard and Pro! I use the DExx-vd_isl with my Sharp X68000 and I noticed there are some fixes and new profiles for it in the latest OSSC Pro release. Could we please see those changes ported over here? Would love to try them out.

Thanks again

**Comment by marqs85** [comment]
That's a good point, it hasn't been updated in a while. I can integrate the changes and generate a new version later this week.

Regarding X68k, the one machine I've tested required sync combiner circuit for a stable picture for yet unknown reason. I didn't see anything strange on the usual H+V sync via scope. Not sure if that applies to your setup.

**Comment by marqs85** [comment]
Version 0.66 is now available with the latest changes integrated.

**Comment by MP2E** [comment]
Thank you very much! I appreciate it

**Comment by MP2E** [comment]
Just tested it out with my X68K and everything is working wonderfully! Now 24khz mode works, which wasn’t the case before

thanks again!!

**Comment by marqs85** [comment]
Out of curiosity, which kind of adapter you use to hook X68k to DExx's SCART input?

**Comment by MP2E** [comment]
I’m using this adapter: https://castlemaniagames.com/products/rondo-products-hd15-2-scart

with a standard VGA video cable and this adapter to hook up to the X68K

https://www.ebay.com/itm/235004706792
